### ISSUE TITLE
jekyll 3.9.0 | The <theme> theme could not be found

### ISSUE THREAD

**Issue by rajBar** [smartergiving/free-nonprofit-starter-website#13]
I am trying to build and test this locally.

However, `jekyll serve` throws an error, then when I add a standard GH-pages Gemfile `bundle exec jekyll serve` also throws and error

What should I put in my local Gemfile to get this working locally?

**Comment by chadokruse** [comment]
Thanks for bringing this to my attention - I forgot this repo existed :) 

The reason for the error is back when I created this five years ago `theme` was not a reserved word. That has since changed.

I went ahead and updated the project to work with Jekyll 3.9, which as of Dec 2021 is the latest version supported by Github Pages. I also added a Gemfile.

Assuming you have [bundler](https://jekyllrb.com/docs/ruby-101/#bundler) installed, you just need to:
1. `bundle install`
2. `bundle exec jekyll build`

**Comment by rajBar** [comment]
worked a charm, thank you sir! :)
